import numpy as np
import scipy
from scipy.io import readsav
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
from scipy.stats import gaussian_kde

istks = readsav('D:/istks.sav')['istks']
continuum = readsav('D:/istks.sav')['continuum']

# displaying data
for i in range(0, 112):
    image_data = istks[i, :, :]
    smoothed_image = scipy.ndimage.gaussian_filter(image_data, sigma=0)
    plt.imshow(smoothed_image, cmap='gray', origin="lower")
plt.axis('off')
plt.title("Intensity Map")
plt.tight_layout()
plt.show()

# Core Points - Polynomial
vertex1 = np.load('core-point_Polynomial.npz')['vertex1']
vertex2 = np.load('core-point_Polynomial.npz')['vertex2']
print("Mean core point (630.15 nm) : ", np.mean(vertex1))
print("Mean core point (630.25 nm) : ", np.mean(vertex2))

# Gaussian Fit
popt1 = np.load('Gaussian-Fit.npz')['Gaussian1']
popt2 = np.load('Gaussian-Fit.npz')['Gaussian2']
def gaussian(x, a, b, c):
    return (a * np.exp(-(x - b)**2 / (2 * c**2)))
in_spectrum = (-1 * (istks[0:112, 0, 0]) + continuum[0][0])
plt.scatter(np.arange(0, 112), in_spectrum[0:112], label="Inverted Spectrum")
plt.plot(np.arange(20, 40), gaussian(np.arange(20, 40), *popt1[0][0]), color='orange')
plt.plot(np.arange(65, 85), gaussian(np.arange(65, 85), *popt2[0][0]), color='orange')
plt.axvline(28.5845979, linestyle=':', color='red', label='630.15 nm')
plt.axvline(74.9904635946, linestyle=':', color='green', label='630.25 nm')
plt.legend(loc="upper right", bbox_to_anchor=(1.1, 1))
plt.title("Inverted Stokes I Spectrum at Pixel (0,0)")
plt.xlabel("Wavelength Index")
plt.ylabel(r'Inverted Stokes I / $I_0$')
plt.tight_layout()
plt.show()

# Brightness Temperature
Conti_Temp1 = np.load('Brightness_Temp.npz')['Temp1']
Conti_Temp2 = np.load('Brightness_Temp.npz')['Temp2']

# Visualizing continuum intensity and its temperature
plt.imshow(continuum, cmap='gray', origin='lower')
plt.title("Continuumgram")
plt.axis('off')
plt.tight_layout()
plt.show()
flat_continuum = [item for sublist in continuum for item in sublist]
plt.hist(flat_continuum, bins=50, edgecolor='black', density=True)
kde = gaussian_kde(flat_continuum)
x = np.linspace(min(flat_continuum), max(flat_continuum), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Continuums")
plt.xlabel("Continuum")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()

plt.imshow(Conti_Temp1, cmap='turbo', origin='lower')
plt.title("Brightness Temperature Map - (630.15 nm)")
plt.colorbar(label='Temperature$_B$ (K)')
plt.axis('off')
plt.tight_layout()
plt.show()
flat_Conti_Temp1 = [item for sublist in Conti_Temp1 for item in sublist]
plt.hist(flat_Conti_Temp1, bins=50, edgecolor='black', density=True)
kde = gaussian_kde(flat_Conti_Temp1)
x = np.linspace(min(flat_Conti_Temp1), max(flat_Conti_Temp1), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Brightness Temperatures - (630.15 nm)")
plt.xlabel("Temperature (K)")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
plt.imshow(Conti_Temp2, cmap='turbo', origin='lower')
plt.title("Brightness Temperature Map - (630.25 nm)")
plt.colorbar(label='Temperature$_B$ (K)')
plt.axis('off')
plt.tight_layout()
plt.show()
flat_Conti_Temp2 = [item for sublist in Conti_Temp2 for item in sublist]
plt.hist(flat_Conti_Temp2, bins=50, edgecolor='black', density=True)
kde = gaussian_kde(flat_Conti_Temp2)
x = np.linspace(min(flat_Conti_Temp2), max(flat_Conti_Temp2), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Brightness Temperatures - (630.25 nm)")
plt.xlabel("Temperature (K)")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()

# Velocity
velocities1 = np.load('Doppler-Velocity.npz')['velocity1']
velocities2 = np.load('Doppler-Velocity.npz')['velocity2']
norm = TwoSlopeNorm(vmin=np.min(velocities1), vcenter=0, vmax=np.max(velocities1))
plt.imshow(velocities1, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label=r"$V_{LOS}$ (km/s)")
plt.title("Line-of-Sight (LOS) Velocity Map (630.15 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()
norm = TwoSlopeNorm(vmin=np.min(velocities2), vcenter=0, vmax=np.max(velocities2))
plt.imshow(velocities2, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label=r"$V_{LOS}$ (km/s)")
plt.title("Line-of-Sight (LOS) Velocity Map (630.25 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()
flat_velocities1 = [item for sublist in velocities1 for item in sublist]
plt.hist(flat_velocities1, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(flat_velocities1)
x = np.linspace(min(flat_velocities1), max(flat_velocities1), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of (LOS) Velocities (630.15 nm)")
plt.xlabel(r"$V_{LOS}$ (km/s)")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
flat_velocities2 = [item for sublist in velocities2 for item in sublist]
plt.hist(flat_velocities2, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(flat_velocities2)
x = np.linspace(min(flat_velocities2), max(flat_velocities2), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of (LOS) Velocities (630.25 nm)")
plt.xlabel(r"$V_{LOS}$ (km/s)")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
plt.scatter(flat_velocities1, flat_continuum)
plt.plot([np.min(flat_velocities1), np.max(flat_velocities1)], [np.max(flat_continuum), np.min(flat_continuum)], color='red')
plt.title(r'Continuum Intensity-$Velocity_{LOS}$ (630.15 nm)')
plt.xlabel(r'$V_{LOS}$ (km/s)')
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.scatter(flat_velocities2, flat_continuum)
plt.plot([np.min(flat_velocities2), np.max(flat_velocities2)], [np.max(flat_continuum), np.min(flat_continuum)], color='red')
plt.title(r'Continuum Intensity-$Velocity_{LOS}$ (630.25 nm)')
plt.xlabel(r'$V_{LOS}$ (km/s)')
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()

# V_Turbulence
E_turb1 = np.load('E_turb.npz')['E_turb1']
E_turb2 = np.load('E_turb.npz')['E_turb2']
plt.imshow(E_turb1, cmap='viridis', origin='lower')
plt.title(r'$\xi_{turb}$ (630.15 nm)')
plt.colorbar(label=r'$\xi_{turb}$ (m/s)')
plt.axis('off')
plt.tight_layout()
plt.show()
E_turb = [item for sublist in E_turb1 for item in sublist]
plt.hist(E_turb, bins=30, edgecolor='black', density=True)
kde = gaussian_kde(E_turb)
x = np.linspace(min(E_turb), max(E_turb), 200)
plt.plot(x, kde(x), 'r-')
plt.title(r'Histogram of Turbulent Velocities - (630.15 nm)')
plt.xlabel(r'$\xi_{turb}$ (m/s)')
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
plt.imshow(E_turb2, cmap='viridis', origin='lower')
plt.title(r'$\xi_{turb}$ (630.25 nm)')
plt.colorbar(label=r'$\xi_{turb}$ (m/s)')
plt.axis('off')
plt.tight_layout()
plt.show()
E_turb = [item for sublist in E_turb2 for item in sublist]
plt.hist(E_turb, bins=35, edgecolor='black', density=True)
kde = gaussian_kde(E_turb)
x = np.linspace(min(E_turb), max(E_turb), 200)
plt.plot(x, kde(x), 'r-')
plt.title(r'Histogram of Turbulent Velocities - (630.25 nm)')
plt.xlabel(r'$\xi_{turb}$ (m/s)')
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()

# Layers Temperature
Temper1 = np.load('temp.npz')['Temper1']
Temper2 = np.load('temp.npz')['Temper2']

Temper = [item for sublist in Temper1[0] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -0.6) - (630.15 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()
Temper = [item for sublist in Temper1[1] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -1.0) - (630.15 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()
Temper = [item for sublist in Temper1[2] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -1.4) - (630.15 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()
Temper = [item for sublist in Temper1[3] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -1.8) - (630.15 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()
Temper = [item for sublist in Temper1[4] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -2.2) - (630.15 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()

Temper = [item for sublist in Temper2[0] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -0.5) - (630.25 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()
Temper = [item for sublist in Temper2[1] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -0.9) - (630.25 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()
Temper = [item for sublist in Temper2[2] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -1.3) - (630.25 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()
Temper = [item for sublist in Temper2[3] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -1.7) - (630.25 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()
Temper = [item for sublist in Temper2[4] for item in sublist]
plt.hist(Temper, bins=10, edgecolor='black')
plt.title(r'Histogram of Temperatures (log $\tau_{500 nm}$ = -2.1) - (630.25 nm)')
plt.xlabel("Temperature (K)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()

# EW
ew1 = [[0]*130 for _ in range (100)]
ew2 = [[0]*130 for _ in range (100)]
for i in range(100):
    for j in range(130):
        ew1[i][j] = np.trapezoid((-1 * (istks[20:40, i, j]) + continuum[i][j])) * 0.00215
        ew2[i][j] = np.trapezoid((-1 * (istks[65:85, i, j]) + continuum[i][j])) * 0.00215
plt.imshow(ew1, cmap='inferno', origin='lower')
plt.title('Equivalent Width (630.15 nm)')
plt.colorbar(label='EW (nm)')
plt.axis('off')
plt.tight_layout()
plt.show()
EW = [item for sublist in ew1 for item in sublist]
plt.hist(EW, bins=50, edgecolor='black', density=True)
kde = gaussian_kde(EW)
x = np.linspace(min(EW), max(EW), 200)
plt.plot(x, kde(x), 'r-')
plt.title(r'Histogram of Equivalent Widths - (630.15 nm)')
plt.xlabel("EW (nm)")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
plt.imshow(ew2, cmap='inferno', origin='lower')
plt.title('Equivalent Width (630.25 nm)')
plt.colorbar(label='EW (nm)')
plt.axis('off')
plt.tight_layout()
plt.show()
EW = [item for sublist in ew2 for item in sublist]
plt.hist(EW, bins=50, edgecolor='black', density=True)
kde = gaussian_kde(EW)
x = np.linspace(min(EW), max(EW), 200)
plt.plot(x, kde(x), 'r-')
plt.title(r'Histogram of Equivalent Widths - (630.25 nm)')
plt.xlabel("EW (nm)")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()

# Line Width
fwhm1 = 2 * abs(popt1[:, :, 2]) * 0.00215 * np.sqrt(2 * np.log(2))
fwhm2 = 2 * abs(popt2[:, :, 2]) * 0.00215 * np.sqrt(2 * np.log(2))
plt.imshow(fwhm1, cmap='inferno', origin='lower')
plt.title('FWHM (630.15 nm)')
plt.colorbar(label='Width (nm)')
plt.axis('off')
plt.tight_layout()
plt.show()
FWHM = [item for sublist in fwhm1 for item in sublist]
plt.hist(FWHM, bins=28, edgecolor='black', density=True)
kde = gaussian_kde(FWHM)
x = np.linspace(min(FWHM), max(FWHM), 200)
plt.plot(x, kde(x), 'r-')
plt.title(r'Histogram of Gaussian FWHMs - (630.15 nm)')
plt.xlabel("FWHM (nm)")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
plt.imshow(fwhm2, cmap='inferno', origin='lower')
plt.title('FWHM (630.25 nm)')
plt.colorbar(label='Width (nm)')
plt.axis('off')
plt.tight_layout()
plt.show()
FWHM = [item for sublist in fwhm2 for item in sublist]
plt.hist(FWHM, bins=45, edgecolor='black', density=True)
kde = gaussian_kde(FWHM)
x = np.linspace(min(FWHM), max(FWHM), 200)
plt.plot(x, kde(x), 'r-')
plt.title(r'Histogram of Gaussian FWHMs - (630.25 nm)')
plt.xlabel("FWHM (nm)")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()

# Line Depth
depth1 = np.load('depth.npz')['depth1']
depth2 = np.load('depth.npz')['depth2']
plt.imshow(depth1, cmap='inferno', origin='lower')
plt.title('Line Depth (630.15 nm)')
plt.colorbar(label='Depth')
plt.axis('off')
plt.tight_layout()
plt.show()
depth = [item for sublist in depth1 for item in sublist]
plt.hist(depth, bins=45, edgecolor='black', density=True)
kde = gaussian_kde(depth)
x = np.linspace(min(depth), max(depth), 200)
plt.plot(x, kde(x), 'r-')
plt.title(r'Histogram of Line Depths - (630.15 nm)')
plt.xlabel(r'Line Depth ($I_{continuum}-I_{core}$)')
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
plt.imshow(depth2, cmap='inferno', origin='lower')
plt.title('Line Depth (630.25 nm)')
plt.colorbar(label='Depth')
plt.axis('off')
plt.tight_layout()
plt.show()
depth = [item for sublist in depth2 for item in sublist]
plt.hist(depth, bins=45, edgecolor='black', density=True)
kde = gaussian_kde(depth)
x = np.linspace(min(depth), max(depth), 200)
plt.plot(x, kde(x), 'r-')
plt.title(r'Histogram of Line Depths - (630.25 nm)')
plt.xlabel(r'Line Depth ($I_{continuum}-I_{core}$)')
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()

# Image Processing
granules_mask = np.load("ImageProcessing.npz")['granules_mask']
intergranules_mask = np.load("ImageProcessing.npz")['intergranules_mask']
granule_areas = np.load("ImageProcessing.npz")['granule_areas']
granule_diameters = np.load("ImageProcessing.npz")['granule_diameters']
granule_perimeters = np.load("ImageProcessing.npz")['granule_perimeters']

print("Number of granules : ", len(granule_areas))
print("Mean Granule Area : ", np.mean(granule_areas))
print("Mean Granule Perimeter : ", np.mean(granule_perimeters))

plt.imshow(continuum,cmap="gray",origin="lower")
plt.contour(granules_mask,origin="lower",colors="red",alpha=0.7)
plt.axis('off')
plt.title("Segmented Continuumgram")
plt.tight_layout()
plt.show()

plt.hist(granule_areas, bins=11, color='goldenrod', edgecolor='black')
plt.title("Histogram of Granules Areas")
plt.xlabel(r"Granule Area (k$m^2$)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()

plt.hist(granule_diameters, bins=11, edgecolor='black')
plt.title("Histogram of Granules Diameters")
plt.xlabel("Granule Diameter (km)")
plt.ylabel("Number of Occurences")
plt.tight_layout()
plt.show()

plt.scatter(granule_areas, granule_perimeters, alpha=0.6)
plt.title("Granules Perimeters vs. Granules Areas")
plt.xlabel(r"Granule Area (k$m^2$)")
plt.ylabel("Granule Perimeter (km)")
plt.plot([np.min(granule_areas), np.max(granule_areas)],
         [np.min(granule_perimeters), np.max(granule_perimeters)], color='red')
plt.tight_layout()
plt.show()

plt.scatter(granule_areas, granule_diameters, alpha=0.6)
plt.title("Granules Diameters vs. Granules Areas")
plt.xlabel(r"Granule Area (k$m^2$)")
plt.ylabel("Granule Diameter (km)")
plt.tight_layout()
plt.show()

# Bisector
bis_all = np.load('Bisector.npz')['bis_all']
levels = np.load('Bisector.npz')['levels']
core1 = np.load("D:/Project/Solar Granulation/core_intensity.npz")['vertex1']
core2 = np.load("D:/Project/Solar Granulation/core_intensity.npz")['vertex2']
 # رسم طیف
x = 89
y = 90
plt.plot(istks[:, y, x])
    # رسم نقاط نیمساز
plt.scatter(bis_all[0,:,y,x], core1[y,x] + levels*(continuum[y,x]-core1[y,x]), zorder=5, label="line 1 bisectors")
plt.scatter(bis_all[1,:,y,x], core2[y,x] + levels*(continuum[y,x]-core2[y,x]), zorder=5, label="line 2 bisectors")
plt.xlabel("Wavelength Index")
plt.ylabel(r'Stokes I / $I_0$')
plt.title("Stokes I Spectrum and Bisectors at Pixel (89,90)")
plt.axvline(28.5845979, linestyle=':', color='red', label='630.15 nm')
plt.axvline(74.9904635946, linestyle=':', color='green', label='630.25 nm')
plt.legend(loc="lower right", bbox_to_anchor=(1.1, 0))
plt.tight_layout()
plt.show()

continuum = [item for sublist in continuum for item in sublist]

bisector = [item for sublist in bis_all[0,0,:,:] for item in sublist]
plt.scatter(bisector, continuum)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(27,31,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.2 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.2 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[0, 0, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.2 Line (630.15 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[0,1,:,:] for item in sublist]
plt.scatter(bisector, continuum)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(27,31,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.4 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.4 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[0, 1, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.4 Line (630.15 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[0,2,:,:] for item in sublist]
plt.scatter(bisector, continuum)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(27,31,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.5 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.5 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[0, 2, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.5 Line (630.15 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[0,3,:,:] for item in sublist]
plt.scatter(bisector, continuum)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(27,31,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.6 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.6 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[0, 3, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.6 Line (630.15 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[0,4,:,:] for item in sublist]
plt.scatter(bisector, continuum)
mask=np.isfinite(bisector)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(27,31,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.75 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.75 Line (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[0, 4, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.75 Line (630.15 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bis1=np.mean(bis_all[0,0,:,:])
bis2=np.mean(bis_all[0,1,:,:])
bis3=np.mean(bis_all[0,2,:,:])
bis4=np.mean(bis_all[0,3,:,:])
bis5=np.mean(bis_all[0,4,:,:])
bis=[bis1,bis2,bis3,bis4,bis5]
plt.scatter(bis, levels)
plt.title("Line Level-Mean Bisector at FOV (630.15 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Line Level")
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[1,0,:,:] for item in sublist]
plt.scatter(bisector, continuum)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(73,78,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.2 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.2 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[1, 0, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.2 Line (630.25 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[1,1,:,:] for item in sublist]
plt.scatter(bisector, continuum)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(73,78,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.4 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.4 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[1, 1, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.4 Line (630.25 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[1,2,:,:] for item in sublist]
plt.scatter(bisector, continuum)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(73,78,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.5 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.5 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[1, 2, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.5 Line (630.25 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[1,3,:,:] for item in sublist]
plt.scatter(bisector, continuum)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(73,78,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.6 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.6 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[1, 3, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.6 Line (630.25 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bisector = [item for sublist in bis_all[1,4,:,:] for item in sublist]
plt.scatter(bisector, continuum)
mask=np.isfinite(bisector)
coeffs = np.polyfit(bisector, continuum, 2)
p = np.poly1d(coeffs)
x_fit=np.linspace(73,78,200)
y_fit=p(x_fit)
plt.plot(x_fit, y_fit, color='red')
plt.title("Continuum Intensity-Bisector at 0.75 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Continuum Intensity")
plt.tight_layout()
plt.show()
plt.hist(bisector, bins=55, edgecolor='black', density=True)
kde = gaussian_kde(bisector)
x = np.linspace(min(bisector), max(bisector), 200)
plt.plot(x, kde(x), 'r-')
plt.title("Histogram of Bisectors at 0.75 Line (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Normalized Number of Occurences")
plt.tight_layout()
plt.show()
bisector = bis_all[1, 4, :, :]
norm = TwoSlopeNorm(vmin=np.min(bisector), vcenter=np.mean(bisector), vmax=np.max(bisector))
plt.imshow(bisector, cmap='bwr', origin='lower', norm=norm)
plt.colorbar(label="Bisector")
plt.title("Bisectors Map at 0.75 Line (630.25 nm)")
plt.axis('off')
plt.tight_layout()
plt.show()

bis1=np.mean(bis_all[1,0,:,:])
bis2=np.mean(bis_all[1,1,:,:])
bis3=np.mean(bis_all[1,2,:,:])
bis4=np.mean(bis_all[1,3,:,:])
bis5=np.mean(bis_all[1,4,:,:])
bis=[bis1,bis2,bis3,bis4,bis5]
plt.scatter(bis, levels)
plt.title("Line Level-Mean Bisector at FOV (630.25 nm)")
plt.xlabel("Bisector Index")
plt.ylabel("Line Level")
plt.tight_layout()
plt.show()
